### ISSUE TITLE
document is wrong in IE8 in script loaded with loadScript

### ISSUE THREAD

**Issue by mintyfloss** [bazaarvoice/scoutfile#7] opened 2015-03-18 15:57 UTC
I ran into problems when using `loadScript` to load the main JS file for Spotlights in IE8. In the main JS file, `document` didn't have the properties and methods that we needed. I noticed that these were undefined: `document.documentElement`, `document.querySelector`, and `document.body`. There are probably many others that are undefined.

To verify that this issue is with `loadScript`, I swapped it out to use https://www.npmjs.com/package/load-script instead, and IE8 was working fine.

**Comment by rmurphey** [comment] 2015-03-18 16:06
Any chance you can provide a test case or example code that demonstrates the issue?

**Comment by mintyfloss** [comment] 2015-03-18 16:07
I can push a branch of Spotlights that shows this.

**Comment by rmurphey** [comment] 2015-03-18 16:08
Since this is an open-source repo, it would be better if you can provide a reduced test case that can be shared publicly. Doesn't need to be today.

**Comment by lawnsea** [comment] 2015-03-18 16:41
None of these occur in the `loadScript` source: `document.documentElement`, `document.querySelector`, and `document.body`.

**Comment by mintyfloss** [comment] 2015-03-18 17:16
@lawnsea The script that I was loading in used them.

**Comment by lawnsea** [comment] 2015-03-18 17:21
So, the script you are loading uses APIs not supported in IE8. Why is that the fault of `loadScript`?

**Comment by mintyfloss** [comment] 2015-03-18 17:35
Maybe I'm confused with what you're talking about, but `document.documentElement`, `document.querySelector`, and `document.body` should be supported in IE8. The reason I think it's an issue with the `loadScript` is because Spotlights work when using another script loader. I'll try to reproduce this issue outside of Spotlights.

**Comment by lawnsea** [comment] 2015-03-18 18:38
> Maybe I'm confused with what you're talking about, but document.documentElement, document.querySelector, and document.body should be supported in IE8.

Whoops, yeah, you're right.

I'm definitely curious to see this reproduced.

**Comment by rmurphey** [comment] 2015-03-18 22:29
@lawnsea the basic repro steps are:

- Create a scout file that loads another script.
- In the loaded script, use `document.body`.
- Run this in IE8.
- Watch things fail.

It's possible that repro is more complex than this, but if it is, then the issue may not be in scoutfile at all. For the record, in @mintyfloss's use case, the actual fix wasn't to use a different script loader, but rather to use `window.document.body` instead of `document.body`.

I'll leave it to @mintyfloss to provide more details and a demonstration of the problem.

**Comment by sirugh** [comment] 2015-04-01 17:37
Unable to repro in IE8 using a very simple script that console logged `document.body` and other things.

**Comment by rmurphey** [comment] 2015-04-01 17:47
@sirugh can you post your test case here or in a gist?

**Comment by sirugh** [comment] 2015-04-01 18:03
https://gist.github.com/sirugh/1c2d4f3c28901a1584cb
This is the index.html and script.js I used.

**Comment by lawnsea** [comment] 2015-05-13 20:22
I just spent a lovely 3 hours with @benhollander root-causing this. The upshot is that once `cleanUp` removes the script from the DOM, `document` in the context of that script is no longer `window.document`.

**Comment by lawnsea** [comment] 2015-05-13 21:48
Removing the `oldIE` ordering hack fixes this. I re-read the [blog post that originally described the hack](http://web.archive.org/web/20130525111405/http://jaubourg.net/2010/07/loading-script-as-onclick-handler-of.html) and saw that the actual problem that it works around is *not* that the callback will be invoked before the script executes, but rather that some other script might execute between the script and the callback. I spoke with @rmurphey about this and we're ok with that.

**Closed** 2015-05-15 20:21 UTC
Labels: bug
